---
title: "Single-cell spatial transcriptomics unravels cell states and ecosystems associated with response to immunotherapy in vulvar high-grade lesions"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### 0. Cell types

Main cell types were assigned using NanoString's InSituType

https://github.com/Nanostring-Biostats/InSituType

### 1. Transfer CosMx cell types on external set:

The following sets were included:

Kong et al. The landscape of immune dysregulation in Crohn’s disease revealed through single-cell transcriptomic profiling in the ileum and colon. Immunity 2023

Bassez et al. A single-cell map of intratumoral changes during  anti-PD1 treatment of patients with breast cancer. Nature Medicine 2021

Kang et al. Systematic dissection of tumor-normal single-cell ecosystems across a thousand tumors of 30 cancer types. Nature Comms 2024

Franken et al. CD4+ T cell activation distinguishes response to anti- PD-L1+anti-CTLA4 therapy from anti-PD-L1. Immunity 2024
monotherapy

Domínguez Conde et al. Cross-tissue immune cell analysis reveals tissue-specific features in humans. Science 2022


Transfer of cell types:

[Click here](https://github.com/roderickslieker/CosMx_vHSIL/blob/master/001_SignaturesAll.md)

Bassez applied:

[Click here](https://github.com/roderickslieker/CosMx_vHSIL/blob/master/002_Bassez_signature_applied.md)

Franken applied:

[Click here](https://github.com/roderickslieker/CosMx_vHSIL/blob/master/003_Franken_applied.md)

Cell type comparison for Conde et al.:

[Click here](https://github.com/roderickslieker/CosMx_vHSIL/blob/master/004_CellTypes_Conde.md)

Cell type comparison for Kong et al.:

[Click here](https://github.com/roderickslieker/CosMx_vHSIL/blob/master/005_Kong_applied.md)

Cell type comparison, normal/tumor Kang et al.:

[Click here](https://github.com/roderickslieker/CosMx_vHSIL/blob/master/006_Kang_applied.md)

